config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  root to: 'homes#top'
  get '/books/tag/:id', to: 'books#index', as: 'tag'

  resources :users
  put "/users/:id/hide" => "users#hide", as: 'users_hide'

  get 'users/:id/edit' => 'users#edit', as: 'users_edit'

  namespace :admin do
     resources :users, only: [:index, :show, :edit, :update]
  end

  resources :books, only: [:new, :create, :destroy, :index, :show, :edit, :update] do
    resources :book_comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  has_many :book_comments
  belongs_to :user

  has_one_attached :image

  validates :title, presence: true
  validates :author, presence: true
  validates :isbn, presence: true

   acts_as_taggable
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
belongs_to :book

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :book
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :books
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :books
         has_many :book_comments

        validates :name, presence: true
        validates :email, presence: true
        validates :encrypted_password, presence: true

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  def self.guest
    find_or_create_by!(email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all.page(params[:page]).per(10)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :is_deleted)
  end

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
    @users = User.all.page(params[:page]).per(10)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "successfully"
      redirect_to edit_admin_path(@user)
    else
      edit_admin_path(@user)
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :is_deleted)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    books_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def authentication_admin_user
    if admin_signed_in?
    elsif user_signed_in?
    else
      redirect_to root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book=Book.find(params[:book_id])
    comment=BookComment.new(book_comment_params)
    comment.book_id=@book.id
    comment.user_id = current_user.id
    comment.save!
     redirect_to book_path(@book.id)
  end

  def destroy
   BookComment.find(params[:book_id]).destroy
   @book = Book.find(params[:id])
    redirect_to book_path(@book.id)
  end

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authentication_admin_user


  def new
    @book = Book.new
  end

  def create
    @book = Book.new(books_params)
    @book.user = current_user

    if @book.save
      redirect_to book_path(@book.id)
    else
      render :new
    end
  end

  def destroy
    Book.find(params[:id]).destroy
    redirect_to books_path
  end

  def index
    if params[:id]
     tag_name = Book.all.tag_counts.find(params[:id]).name
     @books = Book.all.tagged_with(tag_name).order(created_at: :asc).page(params[:page]).per(12)
    else
      @books = Book.all.order(created_at: :asc).page(params[:page]).per(12)
    end
      # 全てのタグを取得したいのですべてのBookデータを配列に格納する
     @bookAll = Book.all
     # book配列に紐づいている、tagをすべて取得する
     @tags_all = @bookAll.tag_counts_on(:tags)
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(books_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def show
    @book=Book.find(params[:id])
    @book_comment = BookComment.new
    if params[:id]
      #gsubでハイフンを取り除く
      result = RakutenWebService::Books::Book.search(isbn: @book.isbn.gsub("-", ""))
      #検索結果の配列の中から
    unless result.first.nil?
      @url = result.first['itemUrl']
      @l_img = result.first['largeImageUrl']
    else
      @url = nil
      @l_img = nil
    end
      # pp '----------------'
      # pp result.first
    end
  end


  private

  def books_params
    params.require(:book).permit(:title, :author, :isbn, :image, :tag_list, :outline, :comment)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def hide
		@user = User.find(params[:id])
    if current_user.email == 'guest@example.com'
      reset_session
      redirect_to :root
    else
    	@user.update(is_deleted: true)
    	reset_session
    	redirect_to root_path
    end
  end

	def edit
	  @user = User.find(params[:id])

	end

  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
  end

private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/admins/admin_helper.rb
module Admins::AdminHelper
end

app/helpers/admins/admins_helper.rb
module Admins::AdminsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_error_messages.html.erb
<% if book.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/books/_form.html.erb
<%= form_with model: book, local:true do |f| %>

  <%= f.label :image, "Image（ISBNから自動取得されます）", class: "text-light" %><br>
  <%= f.file_field :image, accept: "image/*", class: "text-light" %><br>

  <%= f.label :title, "Title", class: "text-light" %><br>
  <%= f.text_field :title %><br>

  <%= f.label :author, "Author", class: "text-light" %><br>
  <%= f.text_field :author %><br>

  <%= f.label :isbn, "ISBN（半角数字で入力）", class: "text-light" %><br>
  <%= f.text_field :isbn, placeholder: "半角数字" %><br>

  <%= f.label :tag_list, "tags（「,」で区切って複数入力）", class: "text-light" %><br>
  <% if @book.tag_list.blank? %>
  <%= f.text_field:tag_list %><br>
  <% else %>
  <%= f.text_field:tag_list, value: @book.tag_list.join(',') %><br>
  <% end %>

  <%= f.label :outline, "outline", class: "text-light" %><br>
  <%= f.text_area :outline %><br>

	<%= f.submit "Post", class: "btn btn-secondary btn-sm" %>
<% end %>

app/views/books/_sidebar.html.erb
<div class="m-5">
  <%= link_to  new_book_path, class:"btn btn-outline-secondary btn-block" do %>
  new
  <% end %>
</div>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th class="text-center text-light">Genres</th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td class="text-center text-light"><%= link_to "List All", books_path %></td>
      </tr>
    <% @tags_all.each do |tag| %>
      <tr>
        <td class="align-middle text-center">
          <%= link_to "#{tag.name}(#{tag.taggings_count})", tag_path(tag.id) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h4 class="text-light p-4 mb-0">Edit Book</h4>
      <div class="form-body p-4">
       <%= render 'form', book: @book %>
      </div>
      <%= link_to 'Back to Book page', book_path %> |
      <%= link_to 'Back to Books index', books_path, class: "back" %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container text-light">
	<div class="row">
		<div class= "col-3">
			<%= render 'sidebar', genres: @genres %>
		</div>
		<div class="col-9">
  		<h2 class="m-5">Books</h2>

			<div class="row mx-auto text-center ">
				<% @books.each do |book| %>
				      <% result = RakutenWebService::Books::Book.search(isbn: book.isbn.gsub("-", "")) %>

				      <% unless result.first.nil?  %>
					      <% @m_img = result.first['mediumImageUrl'] %>
				      <% else %>
					      <% @m_img = nil %>
				      <% end %>
					<div class="col-3 card shadow-lg bg-dark">
						<div class="card-img-top">
							<%= link_to book_path(book.id) ,style: "color: black;", data: {"turbolinks" => false} do %>
								<%  if @m_img %>
    							<%#= image_tag book.image, size: "100x150" %><br>
    							<%= image_tag(@m_img) %><br>
  							<% else %>
    							<%= image_tag 'no_image.jpg', size: "100x100" %><br>
  							<% end %>
  					</div>
  					<div class="card-title text-light">
							<%= book.title %><br>
						</div>
						<% end %>
					</div>
				<% end %>
			</div>
			<div class="col-5 mx-auto">
				<%= paginate @books %>
			</div>
		</div>
	</div>
</div>

app/views/books/new.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h4 class="text-light p-4 mb-0">Post Book</h4>
      <div class="form-body p-4">
        <%= render 'error_messages',book: @book %>
       <%= render 'form', book: @book %>
      </div>
      <%= link_to 'Back to Books index', books_path, class: "back" %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="text-light">
  <div class="container">
    <div class="row">
      <h2 class="col-12 mx-auto">Book detail</h2>
      <div class="col-3 col-sm-4">
           <% if @l_img %>
    							<%= link_to image_tag(@l_img), @url  %>
  							<% else %>
    							<%= image_tag 'no_image.jpg', size: "100x100" %>
  							<% end %>
      </div>
      <div class="col-8 col-sm-8">
        title:「<%= @book.title %>」<br>
        author:　<%= @book.author %><br>
        tag: <%= @book.tag_list.to_s %><br>
        ISBN: <%= @book.isbn %><br>
        outline: <%= @book.outline %><br>
        <% if @book.user == current_user or admin_signed_in? %>
          <%= link_to "Delete", book_path(@book.id), method: :delete,  data: { confirm: '本当に削除しますか？' }, class: "btn-sm btn-outline-danger" %>
          <%= link_to "Edit", edit_book_path(@book.id),  class: "btn-sm btn-outline-light" %>
        <% end %>
      </div>
    </div>
    <div class="row mt-5">
      <h3 class="col-12 mx-auto">comments</h3>
    </div>
      <div class="row">
        <div class="col-4">
          <%= form_with model: [@book, @book_comment], local: false do |f| %>
            <%= f.text_area :comment, rows:'5' %><br>
            <%= f.submit "post" %>
          <% end %>
        </div>
        <div class="col-8 card shadow bg-dark">
          <% @book.book_comments.reverse_each do |book_comment| %>
            <div class="card shadow mb-5 bg-dark">
              <h5 class="card-title"><%= book_comment.user.name %></h5>
              <%= book_comment.created_at.strftime('%Y/%m/%d') %><br>
              <p class="card-text"><%= book_comment.comment %></p>
              <div class="col-3">
                <% if book_comment.user == current_user or admin_signed_in? %>
                  <%= link_to "Delete", book_book_comment_path(book_comment.id), method: :delete,  data: { confirm: '本当に削除しますか？' }, class: "btn-sm btn-outline-danger" %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
  </div>
</div>