config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  root to: 'homes#top'
  get '/books/tag/:id', to: 'books#index', as: 'tag'

  resources :users
  put "/users/:id/hide" => "users#hide", as: 'users_hide'

  get 'users/:id/edit' => 'users#edit', as: 'users_edit'

  namespace :admin do
     resources :users, only: [:index, :show, :edit, :update]
  end

  resources :books, only: [:new, :create, :destroy, :index, :show, :edit, :update] do
    resources :book_comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  has_many :book_comments
  belongs_to :user

  has_one_attached :image

  validates :title, presence: true
  validates :author, presence: true
  validates :isbn, presence: true

   acts_as_taggable
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
belongs_to :book

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :book
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :books
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :books
         has_many :book_comments

        validates :name, presence: true
        validates :email, presence: true
        validates :encrypted_password, presence: true

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  def self.guest
    find_or_create_by!(email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
    end
  end

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
    @users = User.all.page(params[:page]).per(10)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "successfully"
      redirect_to edit_admin_path(@user)
    else
      edit_admin_path(@user)
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :is_deleted)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    books_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def authentication_admin_user
    if admin_signed_in?
    elsif user_signed_in?
    else
      redirect_to root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book=Book.find(params[:book_id])
    comment=BookComment.new(book_comment_params)
    comment.book_id=@book.id
    comment.user_id = current_user.id
    comment.save!
     redirect_to book_path(@book.id)
  end

  def destroy
   BookComment.find(params[:book_id]).destroy
   @book = Book.find(params[:id])
    redirect_to book_path(@book.id)
  end

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authentication_admin_user


  def new
    @book = Book.new
  end

  def create
    @book = Book.new(books_params)
    @book.user = current_user

    if @book.save
      redirect_to book_path(@book.id)
    else
      render :new
    end
  end

  def destroy
    Book.find(params[:id]).destroy
    redirect_to books_path
  end

  def index
    if params[:id]
     tag_name = Book.all.tag_counts.find(params[:id]).name
     @books = Book.all.tagged_with(tag_name).order(created_at: :asc).page(params[:page]).per(12)
    else
      @books = Book.all.order(created_at: :asc).page(params[:page]).per(12)
    end
      # 全てのタグを取得したいのですべてのBookデータを配列に格納する
     @bookAll = Book.all
     # book配列に紐づいている、tagをすべて取得する
     @tags_all = @bookAll.tag_counts_on(:tags)
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(books_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def show
    @book=Book.find(params[:id])
    @book_comment = BookComment.new
    if params[:id]
      #gsubでハイフンを取り除く
      result = RakutenWebService::Books::Book.search(isbn: @book.isbn.gsub("-", ""))
      #検索結果の配列の中から
    unless result.first.nil?
      @url = result.first['itemUrl']
      @l_img = result.first['largeImageUrl']
    else
      @url = nil
      @l_img = nil
    end
      # pp '----------------'
      # pp result.first
    end
  end


  private

  def books_params
    params.require(:book).permit(:title, :author, :isbn, :image, :tag_list, :outline, :comment)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def hide
		@user = User.find(params[:id])
    if current_user.email == 'guest@example.com'
      reset_session
      redirect_to :root
    else
    	@user.update(is_deleted: true)
    	reset_session
    	redirect_to root_path
    end
  end

	def edit
	  @user = User.find(params[:id])

	end

  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
  end

private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/admins/admin_helper.rb
module Admins::AdminHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/edit.html.erb
<div class="container text-light">
 <div class="row">
  <div class="col-md-8 offset-md-1 my-3">
    <h2 class="head-line title_h2 text-center mx-auto">会員情報編集</h2>

   <%= form_with model: @users do |f| %>

  <table>
    <tr>
      <th><%= f.label :ユーザー名 %></th>
      <td><%= f.text_field :name, class:"form-control" %><br>
      </td>
    </tr>

    <tr>
      <th><%= f.label :メールアドレス %></th>
      <td><%= f.text_field :email , class:"form-control"%></td>
    </tr>

    <tr>
      <th><%= f.label :会員ステータス %>
        <%= f.radio_button :is_deleted, :false %>
        <%= f.label :is_deleted, "有効" %>
        <%= f.radio_button :is_deleted, :true %>
        <%= f.label :is_deleted, "退会" %>
      </th>
    </tr>
  </table>


      <div class="row text-right mb-5">
        <%= f.submit "変更を保存する" ,class: "btn btn-success " %>
      </div>
  <% end %>

  </div>

app/views/admins/index.html.erb
<div class="container text-light">
  <div class="row">
    <div class="col-md-8 offset-md-1 my-3">
      <h2 class="head-line title_h2 text-center mx-auto">会員一覧</h2>

    <table class="table-dark table-bordered mx-auto">
      <thead class="thead-dark">
        <tr>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
          <th></th>
        </tr>
      </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.name %></td>
              <td><%= user.email %></td>
              <td>
                <% if user.is_deleted == false %>
                有効
                <% else %>
                無効
                <% end %>
              </td>
              <td>
                <%= link_to "edit", edit_admin_path(user.id) %>
              </td>
            </tr>
            <% end %>
        </tbody>
    </table>

      <div class="mx-auto col-4 mb-5" >
        <%= paginate @users %>
      </dic>

    </div>
  </div>
</div>
</div>

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The book on the sheets</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-dark">
    <header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container">
      <a class="navbar-brand p-3" href="/books">The book on the sheets.</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? or admin_signed_in? %>
            <li class="nav-item">
              <%= link_to "LogOut", destroy_user_session_path, method: :delete, class: 'nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to 'NewPost', new_book_path, class: 'nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Books', books_path, class: 'nav-link text-light' %>
            </li>
            <% if not admin_signed_in? %>
              <li class="nav-item">
                <%= link_to 'MyPage', user_path(current_user.id), class: 'nav-link text-light' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'User index', admin_users_path, class: 'nav-link text-light' %>
              </li>
            <% end %>
          <% else %>
            <li class="nav-item">
              <%= link_to "SignUp", new_user_registration_path, class: 'nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "LogIn", new_user_session_path, class: 'nav-link text-light' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>
    <%= yield %>
  </body>
</html>